# Generated by Django 5.2.15 on 2026-06-26 07:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_seen_visibility',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('connections', 'Connections'), ('nobody', 'Nobody')], db_index=True, default='connections', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='read_receipts_enabled',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['last_seen_visibility'], name='profiles_pr_last_se_800995_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['read_receipts_enabled'], name='profiles_pr_read_re_323ded_idx'),
        ),
    ]
