# Generated by Django 5.2.15 on 2026-07-26 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_email_74c8d6_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_usernam_c0ea66_idx',
        ),
    ]
