# Generated by Django 5.2.15 on 2026-06-26 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_users', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['blocker', 'blocked'], name='connections_blocker_c976ab_idx'), models.Index(fields=['blocked'], name='connections_blocked_ed7261_idx'), models.Index(fields=['created_at'], name='connections_created_c45031_idx')],
                'constraints': [models.UniqueConstraint(fields=('blocker', 'blocked'), name='unique_user_block'), models.CheckConstraint(condition=models.Q(('blocker', models.F('blocked')), _negated=True), name='prevent_self_block')],
            },
        ),
        migrations.CreateModel(
            name='UserRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricted_users', to=settings.AUTH_USER_MODEL)),
                ('restricted_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricted_by_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'restricted_user'], name='connections_owner_i_521f6a_idx'), models.Index(fields=['restricted_user'], name='connections_restric_11ff38_idx'), models.Index(fields=['created_at'], name='connections_created_c5de1b_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'restricted_user'), name='unique_user_restriction'), models.CheckConstraint(condition=models.Q(('owner', models.F('restricted_user')), _negated=True), name='prevent_self_restriction')],
            },
        ),
    ]
