# Generated by Django 5.2.15 on 2026-07-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_userchannelsession_userpresence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('voice', 'Voice Note'), ('document', 'Document')], db_index=True, max_length=20),
        ),
    ]
